source "https://rubygems.org"

gem "jekyll-theme-hydeout", "~> 4.1"

gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end